# 실제 배포 환경용 설정
spring.application.name=shoppingmall-coco
spring.profiles.active=prod

# Cloudinary 키 
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# CORS 설정
cors.allowed-origins=${FRONTEND_URL}